[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake', 'stdenv.cc.cc.lib']

[phases.install]
cmds = []

[phases.build]
cmds = ['npm install --legacy-peer-deps']

[start]
cmd = 'node server.js'
