[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake', 'stdenv.cc.cc.lib']

[phases.install]
cmds = ['cd backend && npm install --legacy-peer-deps']

[phases.build]
cmds = []

[start]
cmd = 'cd backend && node server.js'
